name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - '**'  # Trigger this pipeline whenever a feature branch is pushed

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use the self-hosted runner (Make sure it's set up and online)
    
    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the desired Node.js version (LTS recommended)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run code
      - name: Run code
        run: | 
          npm test  # This will run the tests defined in your package.json file
          npm run start
